org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
kapt.incremental.apt=true

# API base URLs ? override here to change environment without touching build.gradle
RELEASE_BASE_URL=https://a8850aef-d4f5-43e9-9454-8e305de2a107-00-arzq3ozh7h57.pike.replit.dev/api/
# Using your PC's Hotspot IP: 192.168.226.40
DEBUG_BASE_URL=http://192.168.130.40:5000/api/
