import React, { useState, useEffect } from 'react';
import axios from '../../api.js';
let XLSX;
const getXLSX = async () => {
  if (!XLSX) {
    XLSX = await import('xlsx');
  }
  return XLSX;
};
import { BarChart2, Download, AlertTriangle, Bell, TrendingDown, Search } from 'lucide-react';
import { InputField } from '../../components/FormFields';
import { useAuth } from '../../context/AuthContext';

function PctBadge({ pct }) {
  const v = parseFloat(pct) || 0;
  const color = v >= 75 ? 'text-green-700 bg-green-100' : v >= 50 ? 'text-yellow-700 bg-yellow-100' : 'text-red-700 bg-red-100';
  return <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${color}`}>{v}%</span>;
}

export default function TeacherReports() {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState('report');
  const [report, setReport] = useState([]);
  const [subjects, setSubjects] = useState([]);
  const [filters, setFilters] = useState({ subject_id: '', from: '', to: '' });
  const [loading, setLoading] = useState(false);
  const [alertMsg, setAlertMsg] = useState('');

  const [shortlistFilters, setShortlistFilters] = useState({ subject_id: '', from: '', to: '', threshold: 75, search: '' });
  const [shortlist, setShortlist] = useState([]);
  const [shortlistLoading, setShortlistLoading] = useState(false);
  const [shortlistFetched, setShortlistFetched] = useState(false);

  useEffect(() => {
    axios.get('/api/teacher/subjects').then(r => setSubjects(r.data.subjects || []));
  }, []);

  const fetchReport = async () => {
    setLoading(true);
    const params = {};
    if (filters.subject_id) params.subject_id = filters.subject_id;
    if (filters.from) params.from = filters.from;
    if (filters.to) params.to = filters.to;
    try {
      const r = await axios.get('/api/teacher/attendance/report', { params });
      setReport(r.data.report || []);
    } catch {}
    setLoading(false);
  };

  useEffect(() => { fetchReport(); }, []);

  const fetchShortlist = async () => {
    setShortlistLoading(true);
    setShortlistFetched(true);
    try {
      const params = { threshold: shortlistFilters.threshold };
      if (shortlistFilters.subject_id) params.subject_id = shortlistFilters.subject_id;
      if (shortlistFilters.from) params.from = shortlistFilters.from;
      if (shortlistFilters.to) params.to = shortlistFilters.to;
      if (shortlistFilters.search) params.search = shortlistFilters.search;
      const r = await axios.get('/api/teacher/attendance/low-shortlist', { params });
      setShortlist(r.data.students || []);
    } catch {}
    setShortlistLoading(false);
  };

  const buildShortlistRows = (list, meta) => {
    const now = new Date();
    const monthYear = now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
    const today = now.toLocaleDateString('en-IN');
    const dateRange = `${meta.from || 'Beginning'} to ${meta.to || today}`;
    return [
      [`SHORT ATTENDANCE LIST (${monthYear})`],
      [],
      [`Branch    : ${meta.branchName}`],
      [`Semester  : ${meta.semester}`],
      [`Class     : ${meta.className}`],
      [`Subject   : ${meta.subjectName}`],
      [`Date Range: ${dateRange}`],
      [`Threshold : Below ${meta.threshold}%`],
      [`Generated On : ${today}`],
      [`Generated By : ${meta.generatedBy}`],
      [],
      ['Student Name', 'Roll No', 'Address', 'Mobile', 'Total Classes', 'Present', 'Absent', 'Percentage'],
      ...list.map(s => [
        s.name, s.roll_number || s.student_code || '', '',
        s.phone || '', s.total_classes, s.present_count, s.absent_count, `${s.percentage}%`
      ])
    ];
  };

  const getShortlistMeta = () => {
    const sel = subjects.find(s => String(s.id) === String(shortlistFilters.subject_id));
    return {
      subjectName: sel?.name || 'All Subjects',
      branchName: sel?.branch_name || sel?.class_name || '-',
      semester: sel?.semester || '-',
      className: sel?.class_name || '-',
      from: shortlistFilters.from, to: shortlistFilters.to,
      threshold: shortlistFilters.threshold,
      generatedBy: user?.name || '-',
    };
  };

  const exportShortlistCSV = () => {
    if (shortlist.length === 0) { alert('No shortlist data. Generate the shortlist first.'); return; }
    const rows = buildShortlistRows(shortlist, getShortlistMeta());
    const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'low-attendance-shortlist.csv'; a.click();
  };

  const exportShortlistXLSX = async () => {
    if (shortlist.length === 0) { alert('No shortlist data. Generate the shortlist first.'); return; }
    const rows = buildShortlistRows(shortlist, getShortlistMeta());
    const XLSX = await getXLSX();
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = [{ wch: 25 }, { wch: 12 }, { wch: 20 }, { wch: 14 }, { wch: 14 }, { wch: 10 }, { wch: 10 }, { wch: 12 }];
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Low Attendance');
    XLSX.writeFile(wb, 'low-attendance-shortlist.xlsx');
  };

  const sendAlert = async (student) => {
    try {
      await axios.post('/api/teacher/alerts', { student_id: student.student_id });
      setAlertMsg(`Alert sent to ${student.name}`);
      setTimeout(() => setAlertMsg(''), 3000);
    } catch { setAlertMsg('Failed to send alert'); }
  };

  const exportSummaryCSV = () => {
    if (report.length === 0) { alert('No data to export. Generate a report first.'); return; }
    const now = new Date();
    const monthYear = now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
    const today = now.toLocaleDateString('en-IN');
    const selectedSubject = subjects.find(s => String(s.id) === String(filters.subject_id));
    const subjectName = selectedSubject?.name || 'All Subjects';
    const branchName = selectedSubject?.branch_name || selectedSubject?.class_name || '-';
    const semester = selectedSubject?.semester || '-';
    const generatedBy = user?.name || '-';

    const header = [
      [`SUMMARY ATTENDANCE REPORT (${monthYear})`],
      [],
      [`Subject  : ${subjectName}`],
      [`Branch   : ${branchName}`],
      [`Semester : ${semester}`],
      [`Generated On : ${today}`],
      [`Generated By : ${generatedBy}`],
      [],
    ];
    const tableHeader = ['Student', 'Roll No', 'Total Classes', 'Present', 'Absent', 'Percentage'];
    const dataRows = report.map(r => [
      r.name, r.roll_number || r.student_code, r.total_classes, r.present_count, r.absent_count, `${r.percentage}%`
    ]);
    const csv = [...header, tableHeader, ...dataRows].map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'summary-report.csv'; a.click();
  };

  const exportCSV = async () => {
    const now = new Date();
    const monthYear = now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
    const today = now.toLocaleDateString('en-IN');
    const selectedSubject = subjects.find(s => String(s.id) === String(filters.subject_id));
    const subjectName = selectedSubject?.name || 'All Subjects';
    const branchName = selectedSubject?.branch_name || selectedSubject?.class_name || '-';
    const semester = selectedSubject?.semester || '-';
    const generatedBy = user?.name || '-';

    try {
      const params = {};
      if (filters.subject_id) params.subject_id = filters.subject_id;
      if (filters.from) params.from = filters.from;
      if (filters.to) params.to = filters.to;
      const r = await axios.get('/api/teacher/attendance/pivot-report', { params });
      const { dates, report: pivot } = r.data;

      const fmtDate = d => { const [y, m, day] = d.split('-'); return `${day}-${m}-${y}`; };

      const header = [
        [`DAILY ATTENDANCE REPORT (${monthYear})`],
        [],
        [`Subject  : ${subjectName}`],
        [`Branch   : ${branchName}`],
        [`Semester : ${semester}`],
        [`Generated On : ${today}`],
        [`Generated By : ${generatedBy}`],
        [],
      ];
      const tableHeader = ['Student', 'Roll No', ...dates.map(fmtDate), 'Total Classes', 'Present', 'Absent', 'Percentage'];
      const dataRows = pivot.map(row => [
        row.name, row.roll_number || row.student_code,
        ...row.date_values,
        row.total_classes, row.present_count, row.absent_count, `${row.percentage}%`
      ]);

      const csv = [...header, tableHeader, ...dataRows].map(r => r.join(',')).join('\n');
      const blob = new Blob([csv], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a'); a.href = url; a.download = 'attendance-report.csv'; a.click();
    } catch {
      alert('Failed to fetch pivot report. Please try again.');
    }
  };

  return (
    <div className="space-y-4 max-w-2xl mx-auto">
      {alertMsg && <div className="bg-green-50 border border-green-200 text-green-700 text-sm p-3 rounded-xl">{alertMsg}</div>}

      <div className="flex gap-2 overflow-x-auto pb-1">
        <button onClick={() => setActiveTab('report')}
          className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium transition-colors ${activeTab === 'report' ? 'bg-blue-600 text-white' : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'}`}>
          <BarChart2 size={14} /> Attendance Report
        </button>
        <button onClick={() => setActiveTab('shortlist')}
          className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium transition-colors ${activeTab === 'shortlist' ? 'bg-red-500 text-white' : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'}`}>
          <TrendingDown size={14} /> Low Attendance
        </button>
      </div>

      {activeTab === 'report' && (
        <>
          <div className="attendance-card space-y-3">
            <select value={filters.subject_id} onChange={e => setFilters(p => ({ ...p, subject_id: e.target.value }))} className="input-field">
              <option value="">All Subjects</option>
              {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
        <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <div><label className="label text-xs">From</label><input type="date" value={filters.from} onChange={e => setFilters(p => ({ ...p, from: e.target.value }))} className="input-field text-sm" /></div>
              <div><label className="label text-xs">To</label><input type="date" value={filters.to} onChange={e => setFilters(p => ({ ...p, to: e.target.value }))} className="input-field text-sm" /></div>
            </div>
            <button onClick={fetchReport} className="btn-primary w-full">Generate Report</button>
          </div>

          <div className="attendance-card">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-semibold text-gray-700 flex items-center gap-2"><BarChart2 size={16} /> Attendance Report</h3>
              <div className="flex gap-1.5">
                <button onClick={exportSummaryCSV} className="flex items-center gap-1 text-xs btn-secondary py-1.5"><Download size={14} /> Summary</button>
                <button onClick={exportCSV} className="flex items-center gap-1 text-xs btn-secondary py-1.5"><Download size={14} /> Detailed</button>
              </div>
            </div>
            {loading ? <div className="flex justify-center py-8"><div className="animate-spin w-6 h-6 border-2 border-blue-600 border-t-transparent rounded-full" /></div>
              : report.length === 0 ? <p className="text-gray-400 text-sm text-center py-8">No data available</p>
              : (
                <div className="space-y-3">
                  {report.map(r => {
                    const pct = parseFloat(r.percentage) || 0;
                    return (
                      <div key={r.student_id}>
                        <div className="flex items-center justify-between mb-1">
                          <div className="flex-1 min-w-0 mr-2">
                            <p className="text-sm font-medium text-gray-800 truncate">{r.name}</p>
                            <p className="text-xs text-gray-400">{r.student_code} · {r.present_count}/{r.total_classes} classes</p>
                          </div>
                          <div className="flex items-center gap-2">
                            <PctBadge pct={pct} />
                            {pct < 75 && <button onClick={() => sendAlert(r)} title="Send Alert"><Bell size={14} className="text-orange-500" /></button>}
                          </div>
                        </div>
                        <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                          <div className={`h-full rounded-full ${pct >= 75 ? 'bg-green-500' : pct >= 60 ? 'bg-yellow-500' : 'bg-red-500'}`} style={{ width: `${Math.min(pct, 100)}%` }} />
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
          </div>
        </>
      )}

      {activeTab === 'shortlist' && (
        <>
          <div className="attendance-card space-y-3">
            <h3 className="font-semibold text-gray-700 flex items-center gap-2"><TrendingDown size={16} className="text-red-500" /> Low Attendance Shortlist</h3>
            <select value={shortlistFilters.subject_id} onChange={e => setShortlistFilters(p => ({ ...p, subject_id: e.target.value }))} className="input-field">
              <option value="">All My Subjects</option>
              {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <div><label className="label text-xs">From</label><input type="date" value={shortlistFilters.from} onChange={e => setShortlistFilters(p => ({ ...p, from: e.target.value }))} className="input-field text-sm" /></div>
              <div><label className="label text-xs">To</label><input type="date" value={shortlistFilters.to} onChange={e => setShortlistFilters(p => ({ ...p, to: e.target.value }))} className="input-field text-sm" /></div>
            </div>
            <div>
              <label className="label text-xs">Threshold: below <span className="font-bold text-red-600">{shortlistFilters.threshold}%</span></label>
              <input type="range" min="1" max="100" value={shortlistFilters.threshold}
                onChange={e => setShortlistFilters(p => ({ ...p, threshold: parseInt(e.target.value) }))}
                className="w-full h-2 bg-gray-200 rounded-full appearance-none cursor-pointer accent-red-500" />
              <div className="flex justify-between text-xs text-gray-400 mt-0.5"><span>1%</span><span>50%</span><span>100%</span></div>
            </div>
            <InputField icon={Search} value={shortlistFilters.search} onChange={e => setShortlistFilters(p => ({ ...p, search: e.target.value }))}
              placeholder="Search by name or student ID…" inputClassName="text-sm" />
            <button onClick={fetchShortlist} className="w-full py-2 bg-red-500 hover:bg-red-600 text-white rounded-xl text-sm font-medium transition-colors" disabled={shortlistLoading}>
              {shortlistLoading ? 'Generating…' : 'Generate Shortlist'}
            </button>
          </div>

          {shortlistLoading && <div className="flex justify-center py-8"><div className="animate-spin w-6 h-6 border-2 border-red-500 border-t-transparent rounded-full" /></div>}

          {!shortlistLoading && shortlistFetched && (
            <div className="attendance-card">
              <div className="flex items-center justify-between mb-3">
                <h4 className="font-semibold text-gray-700 flex items-center gap-2">
                  <AlertTriangle size={15} className="text-red-500" />
                  {shortlist.length} student{shortlist.length !== 1 ? 's' : ''} below {shortlistFilters.threshold}%
                </h4>
                {shortlist.length > 0 && (
                  <div className="flex gap-1.5">
                    <button onClick={exportShortlistCSV} className="flex items-center gap-1 text-xs btn-secondary py-1.5 border-red-200 text-red-700 hover:bg-red-50">
                      <Download size={13} /> CSV
                    </button>
                    <button onClick={exportShortlistXLSX} className="flex items-center gap-1 text-xs btn-secondary py-1.5 border-red-200 text-red-700 hover:bg-red-50">
                      <Download size={13} /> Excel
                    </button>
                  </div>
                )}
              </div>
              {shortlist.length === 0
                ? <p className="text-gray-400 text-sm text-center py-6">No students below this threshold</p>
                : (
                  <div className="space-y-2">
                    {shortlist.map((s, i) => {
                      const pct = parseFloat(s.percentage) || 0;
                      const critical = pct < 50;
                      return (
                        <div key={i} className={`flex flex-col gap-3 p-3 rounded-xl border sm:flex-row sm:items-center sm:justify-between ${critical ? 'bg-red-50 border-red-200' : 'bg-orange-50 border-orange-100'}`}>
                          <div className="flex-1 min-w-0 mr-2">
                            <div className="flex items-center gap-2">
                              <p className="text-sm font-semibold text-gray-800 truncate">{s.name}</p>
                              {critical && <span className="text-xs bg-red-500 text-white px-1.5 py-0.5 rounded-full font-bold">CRITICAL</span>}
                            </div>
                            <p className="text-xs text-gray-400">{s.student_code} · {s.present_count}/{s.total_classes} classes</p>
                          </div>
                          <div className="flex shrink-0 items-center justify-between gap-2 sm:justify-end">
                            <PctBadge pct={s.percentage} />
                            <button onClick={() => sendAlert(s)} title="Send alert"
                              className="flex items-center gap-1 text-xs bg-orange-100 text-orange-700 px-2 py-1 rounded-lg hover:bg-orange-200 transition-colors">
                              <Bell size={12} /> Alert
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
            </div>
          )}
        </>
      )}
    </div>
  );
}
