import React, { useState, useEffect } from 'react';
import axios from 'axios';
import * as XLSX from 'xlsx';
import { Filter, Download, Search, TrendingDown } from 'lucide-react';
import { InputField } from '../../components/FormFields';
import { useAuth } from '../../context/AuthContext';

export default function AdminReports() {
  const { user } = useAuth();
  const [records, setRecords] = useState([]);
  const [classes, setClasses] = useState([]);
  const [subjects, setSubjects] = useState([]);
  const [filters, setFilters] = useState({ from: '', to: '', class_id: '', subject_id: '' });
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    axios.get('/api/admin/classes').then(r => setClasses(r.data.classes || []));
    axios.get('/api/admin/subjects').then(r => setSubjects(r.data.subjects || []));
  }, []);

  const fetchRecords = async () => {
    setLoading(true);
    const params = {};
    if (filters.from) params.from = filters.from;
    if (filters.to) params.to = filters.to;
    if (filters.class_id) params.class_id = filters.class_id;
    if (filters.subject_id) params.subject_id = filters.subject_id;
    const r = await axios.get('/api/admin/reports', { params });
    setRecords(r.data.records || []);
    setLoading(false);
  };

  const filtered = records.filter(r => !search || r.student_name?.toLowerCase().includes(search.toLowerCase()) || r.student_code?.toLowerCase().includes(search.toLowerCase()));

  const exportSummaryCSV = () => {
    if (records.length === 0) { alert('No data to export. Generate a report first.'); return; }
    const now = new Date();
    const monthYear = now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
    const today = now.toLocaleDateString('en-IN');
    const selectedSubject = subjects.find(s => String(s.id) === String(filters.subject_id));
    const selectedClass = classes.find(c => String(c.id) === String(filters.class_id));
    const subjectName = selectedSubject?.name || 'All Subjects';
    const branchName = selectedClass?.branch_name || '-';
    const semester = selectedClass?.semester || '-';
    const generatedBy = user?.name || '-';

    const studentMap = {};
    records.forEach(r => {
      const sid = r.student_id;
      if (!studentMap[sid]) {
        studentMap[sid] = { name: r.student_name, roll: r.roll_number || r.student_code, total: 0, present: 0 };
      }
      studentMap[sid].total += 1;
      if (r.status === 'present') studentMap[sid].present += 1;
    });

    const header = [
      [`SUMMARY ATTENDANCE REPORT (${monthYear})`],
      [],
      [`Subject  : ${subjectName}`],
      [`Branch   : ${branchName}`],
      [`Semester : ${semester}`],
      [`Generated On : ${today}`],
      [`Generated By : ${generatedBy}`],
      [],
    ];
    const tableHeader = ['Student', 'Roll No', 'Total Classes', 'Present', 'Absent', 'Percentage'];
    const dataRows = Object.values(studentMap).map(s => {
      const absent = s.total - s.present;
      const pct = s.total > 0 ? (Math.round(1000 * s.present / s.total) / 10) : 0;
      return [s.name, s.roll, s.total, s.present, absent, `${pct}%`];
    });

    const csv = [...header, tableHeader, ...dataRows].map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'admin-summary-report.csv'; a.click();
  };

  const exportCSV = async () => {
    const now = new Date();
    const monthYear = now.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
    const today = now.toLocaleDateString('en-IN');
    const selectedSubject = subjects.find(s => String(s.id) === String(filters.subject_id));
    const selectedClass = classes.find(c => String(c.id) === String(filters.class_id));
    const subjectName = selectedSubject?.name || 'All Subjects';
    const branchName = selectedClass?.branch_name || '-';
    const semester = selectedClass?.semester || '-';
    const generatedBy = user?.name || '-';

    try {
      const params = {};
      if (filters.from) params.from = filters.from;
      if (filters.to) params.to = filters.to;
      if (filters.class_id) params.class_id = filters.class_id;
      if (filters.subject_id) params.subject_id = filters.subject_id;
      const r = await axios.get('/api/admin/reports/pivot', { params });
      const { dates, report: pivot } = r.data;

      if (!pivot || pivot.length === 0) { alert('No data to export.'); return; }

      const fmtDate = d => { const [y, m, day] = d.split('-'); return `${day}-${m}-${y}`; };

      const header = [
        [`DAILY ATTENDANCE REPORT (${monthYear})`],
        [],
        [`Subject  : ${subjectName}`],
        [`Branch   : ${branchName}`],
        [`Semester : ${semester}`],
        [`Generated On : ${today}`],
        [`Generated By : ${generatedBy}`],
        [],
      ];
      const tableHeader = ['Student', 'Roll No', ...dates.map(fmtDate), 'Total Classes', 'Present', 'Absent', 'Percentage'];
      const dataRows = pivot.map(row => [
        row.name, row.roll_number || row.student_code,
        ...row.date_values,
        row.total_classes, row.present_count, row.absent_count, `${row.percentage}%`
      ]);

      const csv = [...header, tableHeader, ...dataRows].map(row => row.join(',')).join('\n');
      const blob = new Blob([csv], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a'); a.href = url; a.download = 'admin-attendance-report.csv'; a.click();
    } catch {
      alert('Failed to fetch pivot report. Please try again.');
    }
  };

  return (
    <div className="space-y-4 max-w-2xl mx-auto">
      <div className="attendance-card space-y-3">
        <h3 className="font-semibold text-gray-700 flex items-center gap-2"><Filter size={16} /> Global Filters</h3>
        <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
          <div><label className="label text-xs">From Date</label><input type="date" value={filters.from} onChange={e => setFilters(p => ({...p, from: e.target.value}))} className="input-field text-sm" /></div>
          <div><label className="label text-xs">To Date</label><input type="date" value={filters.to} onChange={e => setFilters(p => ({...p, to: e.target.value}))} className="input-field text-sm" /></div>
        </div>
        <select value={filters.class_id} onChange={e => setFilters(p => ({...p, class_id: e.target.value}))} className="input-field">
          <option value="">All Classes</option>
          {classes.map(c => <option key={c.id} value={c.id}>{c.name} {c.section} - Sem {c.semester}</option>)}
        </select>
        <select value={filters.subject_id} onChange={e => setFilters(p => ({...p, subject_id: e.target.value}))} className="input-field">
          <option value="">All Subjects</option>
          {subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
        </select>
        <button onClick={fetchRecords} className="btn-primary w-full">Generate Report</button>
      </div>

      {records.length > 0 && (
        <div className="attendance-card">
          <div className="flex gap-2 mb-3">
            <InputField icon={Search} className="flex-1" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search..." />
            <button onClick={exportSummaryCSV} title="Download Summary Report" className="btn-secondary px-2 text-xs flex items-center gap-1"><Download size={14} /> Summary</button>
            <button onClick={exportCSV} title="Download Detailed Report" className="btn-secondary px-2 text-xs flex items-center gap-1"><Download size={14} /> Detailed</button>
          </div>
          <div className="text-sm text-gray-500 mb-3">Showing {filtered.length} of {records.length} records</div>
          {loading ? <div className="flex justify-center py-8"><div className="animate-spin w-6 h-6 border-2 border-purple-600 border-t-transparent rounded-full" /></div>
          : <div className="space-y-2">
            {filtered.slice(0, 200).map(r => (
              <div key={r.id} className="flex items-center justify-between gap-3 py-2 border-b border-gray-50 last:border-0">
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium text-gray-800 truncate">{r.student_name}</p>
                  <p className="text-xs text-gray-400 truncate">{r.student_code} • {r.subject_name}</p>
                  <p className="text-xs text-gray-400">{new Date(r.date).toLocaleDateString('en-IN')} • {r.method}</p>
                </div>
                <span className={`${r.status === 'present' ? 'badge-present' : 'badge-absent'} shrink-0`}>{r.status}</span>
              </div>
            ))}
          </div>}
        </div>
      )}
    </div>
  );
}
